### PR TITLE
Add file used for docker builds and deployments

### PR DESCRIPTION
**Pull request by bparli**
This is what I've been using locally to build and deploy a traefik image.  It should look familiar (tweety, sidecar)

- Nitro Dockerfile to build a traefik image using s6

- Necessary S6 files

- build.sh for convenience

ping @mihaitodor @relistan @felixgborrego

### CODE REVIEW

**Comment by mihaitodor** [comment]
A few questions here:
- I'm not sure I get how this works, because if you have this repo stored locally in `$GOPATH/src/github.com/Nitro/traefik`, it will look for submodules in `$GOPATH/src/github.com/containous/traefik`, which won't work. Or, have you cloned this repo manually under `$GOPATH/src/github.com/containous/traefik`?

- how are you specifying the TOML config inside the container?

**Comment by bparli** [comment]
The repo is cloned at $GOPATH/src/github.com/containous/traefik.  I'm actually not sure how it would work otherwise.

The TOML files are mounted, only because I found it easier to verify what is deployed.  See here for the /etc/traefik mount: [https://github.com/Nitro/erector/blob/master/roles/traefik/tasks/main.yml](https://github.com/Nitro/erector/blob/master/roles/traefik/tasks/main.yml)

**Comment by mihaitodor** [comment]
Ah, I see. OK. That's probably the easiest way. Using the make scripts would allow you to clone the Nitro fork in `$GOPATH/src/github.com/Nitro/traefik`, because they simply map the files to `$GOPATH/src/github.com/containous/traefik` inside a container before building.

**Comment by bparli** [comment]
@mihaitodor Any further concerns on this? Good to merge?

**Comment by mihaitodor** [comment]
Nope, sheep it :)

**Pull request merged**
